### ISSUE TITLE
Finger inertias have wrong orientations

### ISSUE THREAD

**Issue by lgulich** [FFTAI/Wiki-GRx-Models#3]
The inertias of the fingers (*_proximal and *_intermediate links) in the URDF model [here](https://github.com/FFTAI/Wiki-GRx-Models/blob/master/GRX/GR1/GR1T2/urdf/GR1T2_fourier_hand.urdf) seem to have the wrong orientation.

I would expect that the inertia boxes are aligned with the fingers. Please see the attached image for reference (the inertia boxes are visualized in turquoise). I would expect that the inertia boxes are aligned with the fingers.

![image](https://github.com/user-attachments/assets/7224cecc-9fc8-4b9b-9e1f-8d47ac256224)

**Comment by CarlHu6** [comment]
Thank you for your issue! We will fix it shortly and I will let you know when it fixed

**Comment by CarlHu6** [comment]
Hi, the inertia orientation error has been fixed, you may check it with the updated urdf

**Comment by CarlHu6** [comment]
Hi, the inertia orientation error has been fixed, you could check it with the updated urdf. #7f186d42d1616e4803e454a879991aaf8c9de8b4

I have show the figure below:
![Screenshot from 2024-10-16 20-18-02](https://github.com/user-attachments/assets/b1199301-94f2-4f69-8fae-c73dc50683ec)
